### ISSUE TITLE
Support Region Queries

### ISSUE THREAD

**Issue by gtudan** [PSPDFKit-labs/browserslist.dev#16] opened 2021-02-02 09:53 UTC
Canisuse should support region queries like `> 5% in US` but they don't seem to work on the site. 
It would be cool if the site would support those!

**Comment by ritz078** [comment] 2021-07-15 07:44
This is a duplicate of #13.

We are looking into this. We can move browserslist to the server.

**Closed** 2021-07-15 07:45 UTC
